### ISSUE TITLE
crash on world load 1.15.2(cobalt related items)toolbuilder-2.0.1

### ISSUE THREAD

**Issue by SDUBZ** [MarioAndWeegee3/Tool-Builder#18] opened 2020-02-01 20:14 UTC
log:
https://paste.ee/p/Aimw3

**Comment by MarioAndWeegee3** [comment] 2020-02-02 00:46
The crash is caused by AnimalNet, see line 3044. (The Cobalt thing is being handled)

**Comment by MarioAndWeegee3** [comment] 2020-02-02 01:01
Fixed in 2.0.2

**Closed as completed by MarioAndWeegee3** 2020-02-02 01:01 UTC
